apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudtrader-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudtrader-ui
  template:
    metadata:
      labels:
        app: cloudtrader-ui
    spec:
      containers:
      - name: cloudtrader-ui
        image: cloudtrader.azurecr.io/cloudtrader-ui:v2
        ports:
        - containerPort: 80
        env:
          - name: API_URL
            value: 'http://cloudtrader-api'